import { IstanzeDescriptorInterface } from './../../../config/network/api.descriptors';
import { Istanza } from './../istanza.model';

export class istanzaFactory{
    static create(descriptor: IstanzeDescriptorInterface): Istanza{
        const istance: Istanza = new Istanza();
        const keysToDuplicate = [
            'id',
            'id_ram',
            'nome',
            'cognome',
            'luogo_nascita',
            'prov_nascita',
            'data_nascita',
            'comune_residenza',
            'prov_residenza',
            'indirizzo_residenza',
            'civico_residenza',
            'cap_residenza',
            'email_richiedente',
            'tipo_dichiarante',
            'ragione_sociale',
            'comune_impr',
            'prov_impr',
            'indirizzo_impr',
            'civico_impr',
            'cap_impr',
            'pref_tel_impr',
            'num_tel_impr',
            'email_impr',
            'piva',
            'cf',
            'tipo_impresa',
            'pec_impr',
            'codice_albo',
            'codice_ren',
            'cciaa_prov',
            'cciaa_codice',
            'cciaa_data',
            'codice_ateco',
            'banca_istituto',
            'banca_agenzia',
            'iban_it',
            'iban_num_chk',
            'iban_cin',
            'iban_abi',
            'iban_cab',
            'iban_cc',
            'nv1' ,
            'sp1',
            'rott1',
            'nv2',
            'sp2',
            'rott2',
            'nv3',
            'sp3',
            'rott3',
            'nv4',
            'sp4',
            'rott4',
            'nv5',
            'sp5',
            'rott5',
            'nv6',
            'sp6',
            'rott6',
            'nv7',
            'sp7',
            'rott7',
            'nv8',
            'sp8',
            'rott8',
            'nv9',
            'sp9',
            'rott9',
            'nv10',
            'sp10',
            'rott10',
            'nv11',
            'sp11',
            'r_nv_1',
            'r_sp_1',
            'r_rott_1',
            'r_nv_2',
            'r_sp_2',
            'r_rott_2',
            'r_nv_3',
            'r_sp_3',
            'r_rott_3',
            'rim_nv_1',
            'rim_sp_1',
            'rim_rott_1',
            'rim_nv_2',
            'rim_sp_2',
            'rim_rott_2',
            'rim_nv_3',
            'rim_sp_3',
            'pmi',
            'rete',
            'data_istanza',
            'note',
            'caricamento',
            'pec_msg_identificativo',
            'pec_msg_id',
            'eliminata',
            'user',
            'data_agg',
            'tipo_istanza',

        ];

        keysToDuplicate.forEach(key=> {

            istance[key] = descriptor[key];
        });
        return istance;
    }
}
